name: forLaba7
on:
  push:
    branches: [ Lab7 ]
  pull_request:
    branches: [ Lab7 ]
jobs: 
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: compiling and test
      run: |
            cd LABA7
            make
            make testA
            make testB
            
    - name: testing
      run: |
            cd LABA7
            echo 1 > input.txt
            echo 4 >> input.txt
            echo 3 >> input.txt
            #./testA < input.txt
            Get-Content input.txt | .\testA
            ./testB

            make testAreport
            make testBreport

