  
name: forLaba4
on:
  push:
    branches: [ Lab4 ]
  pull_request:
    branches: [ Lab4 ]
jobs: 
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: install valgrind and splint
      run: |
            sudo apt install valgrind
            sudo apt install splint
    - name: compiling and test TASK 1
      working-directory: ./LABA4
      run: |
            make task1
            make test1
            
    - name: check code with valgrind
      run: |
            echo 345 > input.txt
            echo 5 >> input.txt 
            valgrind ./task1 < input.txt 
    - name: check code with slint
      run: |
            make splint_test1
    - name: compiling and test TASK2
      run: |
            make task2
            make test2
              
    - name: check code with valgrind
      run: |
            valgrind ./task2
    - name: check code with slint
      run: |
            splint_test2
