name: forLaba7
on:
  push:
    branches: [ Lab7 ]
  pull_request:
    branches: [ Lab7 ]
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: compiling and test
      run: |
            cd LABA7
            make
            make testA
            make testB
            
    - name: testing
      run: |
            cd LABA7
            echo "ss" > input.txt
            echo 0 >> input.txt
            echo 4 >> input.txt
            echo 3 >> input.txt
            ./testA < input.txt
            #Get-Content input.txt | .\testA
            #cmd /c '.\testA.exe < input.txt' 
            ./testB

            make testAreport
            make testBreport
            
    - name: Upload results
      uses: codecov/codecov-action@v1
      with: 
       files: |
         ./LABA7/bookshop.c.gcov
         ./LABA7/answer.c.gcov

    - name: Testing memory
      run: |
            cd LABA7
            rm *.gc*
            make testBlim
            ./testBlim
            make testBlimreport

    - name: Upload results for memory 
      uses: codecov/codecov-action@v1
      with: 
       files: |
         ./LABA7/bookshop.c.gcov

    - name: splint test
      run: |
            sudo apt-get install splint
            cd LABA7
            splint -nullassign -boolops -retvalint -predboolint -compdestroy +ignoresigns lab7progect.c 

