name: forLaba2
on:
  push:
    branches: [ Lab2 ]
  pull_request:
    branches: [ Lab2 ]
jobs:
  testing:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: compiling and test
        run: |
              make -C Laba2/
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install valgrind and splint
        run: |
              sudo apt install valgrind
              #sudo pip install cpplint 
              sudo apt install splint
      - name: install conio.h
        run: |
              git clone https://github.com/zoelabbb/conio.h
              cd conio.h
              sudo mv conio.h /usr/include/
              cd ..
      - name: compiling and test 
        run: |
              make -C Laba2/
      - name: check code with valgrind
        run: |
              cd Laba2
              cd bin
              echo 9 > input.txt
              valgrind ./main < input.txt
              #uncomm if valgrind give error
              #valgrind --leak-check=full ./main < input.txt
              cd ..
          
              
              
  
              
        
        
        
        
