name: forLaba2
on:
  push:
    branches: [ Lab2 ]
  pull_request:
    branches: [ Lab2 ]
jobs:
  testing:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: compiling and test
        run: |
              make -C Laba2/
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: install valgrind and cpplint
        run: |
              sudo apt install valgrind
              sudo pip install cpplint 
              find ./Laba2 -horoscope *.h -horoscope *.c | xargs cpplint
